name: 'Setup Node.js'
description: 'Setup Node.js with the version specified in package.json engines'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # actions/setup-node@v6
      with:
        node-version: '24.x'
        cache: 'npm'

    - name: Install npm
      shell: bash
      run: |
        node -v
        npm install -g "npm@>=12.0.1"
        npm -v
