# From https://github.com/dependabot/dependabot-core/blob/main/.github/dependabot.yml
version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'friday'
    cooldown:
      default-days: 7
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'friday'
    cooldown:
      default-days: 7
    groups:
      dev-dependencies-major:
        dependency-type: 'development'
        update-types:
          - major
      prod-dependencies-major:
        dependency-type: 'production'
        update-types:
          - major
      dev-dependencies-minor:
        dependency-type: 'development'
        update-types:
          - minor
          - patch
      prod-dependencies-minor:
        dependency-type: 'production'
        update-types:
          - minor
          - patch
