import { Ingredient } from './Ingredient';

const Scents: Set<Ingredient> = new Set();

Scents.add(Ingredient.AmyrisBalsamiferaBarkOil);
Scents.add(Ingredient.ArtemisiaPallensFlowerOil);
Scents.add(Ingredient.BetaPinene);
Scents.add(Ingredient.BoswelliaCarteriOil);
Scents.add(Ingredient.BulnesiaSarmientoiWoodOil);
Scents.add(Ingredient.CanangaOdorataFlowerOil);
Scents.add(Ingredient.Cinnamal);
Scents.add(Ingredient.Citral);
Scents.add(Ingredient.CistusLadaniferusResin);
Scents.add(Ingredient.CistusLadaniferusResinAbsolute);
Scents.add(Ingredient.CitrusAurantifoliaLimeOil);
Scents.add(Ingredient.CitrusAurantiumAmaraLeafTwigOil);
Scents.add(Ingredient.CitrusAurantiumBergamiaFruitOil);
Scents.add(Ingredient.CitrusAurantiumDulcisFruitExtract);
Scents.add(Ingredient.CitrusAurantiumDulcisOrangePeelOil);
Scents.add(Ingredient.CitrusGrandisPeelOil);
Scents.add(Ingredient.CitrusLimonPeelOil);
Scents.add(Ingredient.CoriandrumSativumFruitOil);
Scents.add(Ingredient.CymbopogonMartiniPalmarosaOil);
Scents.add(Ingredient.DimethylHeptenal);
Scents.add(Ingredient.EssentialOil);
Scents.add(Ingredient.EucalyptusGlobusLeafOil);
Scents.add(Ingredient.EugeniaCaryphyllusLeafOil);
Scents.add(Ingredient.FerulGalbaniferaResinOil);
Scents.add(Ingredient.FoeniculumVulgareOil);
Scents.add(Ingredient.Fragrance);
Scents.add(Ingredient.GammaDecalactone);
Scents.add(Ingredient.GammaNonalactone);
Scents.add(Ingredient.Geraniol);
Scents.add(Ingredient.Heliotropine);
Scents.add(Ingredient.HexylCinnamal);
Scents.add(Ingredient.IlliciumVerumFruitSeedOil);
Scents.add(Ingredient.IsoamylSalicylate);
Scents.add(Ingredient.JuniperusMexicanaCedarOil);
Scents.add(Ingredient.JuniperusVirginianaCedarwoodOil);
Scents.add(Ingredient.LavandulAngustifoliaOil);
Scents.add(Ingredient.LavandulaHybridaLavandinOil);
Scents.add(Ingredient.LavandulaHybridaOil);
Scents.add(Ingredient.Limonene);
Scents.add(Ingredient.Linalool);
Scents.add(Ingredient.MenthaArvensisLeafOil);
Scents.add(Ingredient.MyroxylonPereiraeOil);
Scents.add(Ingredient.PelargoniumGraveolensFlowerOil);
Scents.add(Ingredient.PhenethylAlcohol);
Scents.add(Ingredient.PogostemonCablinLeafExtract);
Scents.add(Ingredient.PogostemonCablinOil);
Scents.add(Ingredient.RosaDamascenaFlowerExtract);
Scents.add(Ingredient.RosmarinusOfficinalisLeafOil);
Scents.add(Ingredient.SalviaSclaraeOil);
Scents.add(Ingredient.StyraxTonkinensisResinExtract);
Scents.add(Ingredient.ThreeHexenol);
Scents.add(Ingredient.Vanillin);

export { Scents };
