name: CI - Pull Request Checks

on:
  pull_request:
    branches: [main]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # actions/checkout@v7.0.1

      - name: Setup Node.js
        uses: ./.github/actions/setup-node

      - name: Install dependencies
        run: npm ci

      - name: Run Lint
        run: npm run lint

      - name: Type check
        run: npm run type-check

      - name: Run tests
        run: npm test

      - name: Build application
        run: npm run build:prod

      - name: Run Format
        run: npm run format
