name: Dependabot auto-merge
on:
  pull_request:
    branches: ['main']
    paths:
      - '**/package.json'
      - '**/package-lock.json'
      - '.github/**'
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: read

jobs:
  dependabot:
    runs-on: ubuntu-slim
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Verify Dependabot
        run: |
          if [[ "${{ github.event.sender.type }}" != "Bot" || "${{ github.event.sender.login }}" != "dependabot[bot]" ]]; then
            echo "This PR is not from Dependabot."
            exit 1
          fi

      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # actions/create-github-app-token@v3.2.0
        with:
          client-id: ${{ vars.RELEASE_PLEASE_CLIENT_ID }}
          private-key: ${{ secrets.RELEASE_PLEASE_APP_PRIVATE_KEY }}

      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{steps.app-token.outputs.token}}
